name: Java APP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4
        
    - name: Build with Maven
      run: cd java-app && mvn clean package
      
    # - name: Build Docker image
    #   run: |
    #     cd java-app
    #     docker build -t my-java-app . 

    - name: Build and Tag and Push Docker Image to ACR
      run: |
        az acr login --name ${{ secrets.ACR_NAME }} 
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/crud-app:${{env.IMAGE_TAG}} .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/crud-app:${{env.IMAGE_TAG}} 
