name: Java APP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4
      

    - name:  Build with Maven
      run: mvn clean package --no-transfer-progress


    - name: build docker image
      run: |
        docker build -t my-java-app . 
