name: Java APP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_NAME: javaappacr
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
  
    - name: Build with Maven
      run: cd java-app && mvn clean package

    - name: login to ACR
      run: az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build and Push Docker Image to ACR
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} java-app
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} 
