name: Java APP CD

on:
  workflow_run:
    workflows: ["Java APP CI"]
    types:
      - completed
  workflow_dispatch:

# Add permissions for OIDC authentication
permissions:
  id-token: write
  contents: read

env: 
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_NAME: java-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login to Azure using workload identity federation (managed identity)
      - name: Azure login with managed identity
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # For Azure Web App deployment (uncomment and modify as needed)
      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name ${{ secrets.WEB_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io
      
      # Set Application Insights connection string as an app setting
      - name: Configure Application Insights
        run: |
          az webapp config appsettings set \
            --name ${{ secrets.WEB_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --settings APPLICATIONINSIGHTS_CONNECTION_STRING="${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}"
      
      - name: Restart Azure Web App
        run: |
          az webapp restart --name ${{ secrets.WEB_APP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }}
         
