name: Java APP CD

on:
  workflow_run:
    workflows: ["Java APP CI"]
    types:
      - completed

env: 
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Deploy to Azure Web App
      #   run: |
      #       az webapp config container set \
      #       --name ${{ secrets.WEB_APP_NAME }} \
      #       --resource-group ${{ secrets.RESOURCE_GROUP }} \
      #       --container-image-name ${{ secrets.ACR_NAME }}.azurecr.io/crud-app:${{ env.IMAGE_TAG }} \
      #       --container-registry-url https://${{ secrets.ACR_NAME }}.azurecr.io
      
      # - name: Restart Azure Web App
      #   run: |
      #       az webapp restart --name ${{ secrets.WEB_APP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }}
         
